apiVersion: v1
name: rancher-eks-operator
description: A Helm chart for provisioning EKS clusters
home: https://github.com/rancher/eks-operator
sources:
  - "https://github.com/rancher/eks-operator"
version: 1.0.800
appVersion: v1.0.8
